from __future__ import annotations

from typing import Any

from apify_client import ApifyClient

from config import settings
from config.icp import YOUTUBE_SEARCH_TERMS

_client: ApifyClient | None = None


def _get_client() -> ApifyClient:
    global _client
    if _client is None:
        _client = ApifyClient(settings.APIFY_API_TOKEN)
    return _client


def get_channel_data(channel_url: str) -> dict[str, Any] | None:
    """Fetch channel metadata and recent videos from a YouTube channel URL."""
    client = _get_client()
    run_input = {
        "startUrls": [{"url": channel_url}],
        "maxResults": 20,
        "maxResultsShorts": 10,
        "downloadSubtitles": False,
        "hasCC": False,
        "isHD": False,
        "isHDR": False,
        "is360": False,
        "is3D": False,
        "isLive": False,
        "isVR180": False,
        "preferAutoGeneratedSubtitles": False,
        "subtitlesLanguage": "en",
    }

    try:
        run = client.actor(settings.APIFY_YOUTUBE_ACTOR).call(run_input=run_input)
        items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
    except Exception as exc:
        print(f"  YouTube scrape failed for {channel_url}: {exc}")
        return None

    if not items:
        return None

    videos = []
    channel_info: dict[str, Any] = {}

    for item in items:
        if item.get("type") == "channel":
            channel_info = item
        elif item.get("type") in ("video", "short"):
            videos.append({
                "title": item.get("title"),
                "url": item.get("url"),
                "views": item.get("viewCount"),
                "likes": item.get("likes"),
                "description": (item.get("description") or "")[:500],
                "publishedAt": item.get("date"),
                "duration": item.get("duration"),
            })

    return {
        "channel_url": channel_url,
        "channel_name": channel_info.get("channelName") or channel_info.get("title"),
        "subscriber_count": channel_info.get("subscriberCount"),
        "video_count": channel_info.get("videoCount"),
        "description": (channel_info.get("description") or "")[:1000],
        "videos": videos[:20],
    }


def search_channels_by_keyword(
    keywords: list[str] | None = None,
    results_per_keyword: int = 20,
) -> list[str]:
    """Search YouTube by keyword and return channel URLs."""
    keywords = keywords or YOUTUBE_SEARCH_TERMS
    client = _get_client()
    channel_urls: set[str] = set()

    print(f"  Searching YouTube for {len(keywords)} terms...")

    for keyword in keywords:
        run_input = {
            "searchKeywords": keyword,
            "maxResults": results_per_keyword,
            "type": "channel",
        }
        try:
            run = client.actor(settings.APIFY_YOUTUBE_ACTOR).call(run_input=run_input)
            items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
            for item in items:
                url = item.get("url") or item.get("channelUrl")
                if url and ("youtube.com/channel" in url or "youtube.com/@" in url or "youtube.com/c/" in url):
                    channel_urls.add(url)
            print(f"    '{keyword}' → {len(items)} channels")
        except Exception as exc:
            print(f"    '{keyword}' failed: {exc}")

    print(f"  Found {len(channel_urls)} unique YouTube channels.")
    return list(channel_urls)
